spring.application.name=workshop-platform

spring.datasource.url=jdbc:mysql://localhost:3306/workshop_platform?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Snehalatha@07
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

server.port=8080

app.jwt.secret=YXBwLXdvcmtzaG9wLXBsYXRmb3JtLXN1cGVyLXNlY3JldC1rZXktMzItaW4tbGVuZ3Ro
app.jwt.expiration-ms=86400000
